<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Form2Answer;
use App\Enums\Form2ImunizedReason;
use App\Enums\ImunizedInformationSource;

class Form2Seeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        Form2Answer::create([
            'house_id' => '1',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Tono',
            'child_name' => 'Raka',
            'birthdate' => '2010-02-06 00:00:00',
            'gender' => 'l',
            'q1' => 'y',
            'q2' => 't',
            'q3' => 'y',
            'q4' => 't',
            'q5' => Form2ImunizedReason::OP3,
            'q6' => 'y',
            'q7' => ImunizedInformationSource::OP6,
            'q8' => 'y',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '1',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Ujang',
            'child_name' => 'Tari',
            'birthdate' => '2013-08-11 00:00:00',
            'gender' => 'p',
            'q1' => 'y',
            'q2' => 't',
            'q3' => 'y',
            'q4' => 't',
            'q5' => Form2ImunizedReason::OP5,
            'q6' => 'y',
            'q7' => ImunizedInformationSource::OP4,
            'q8' => 'y',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '1',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Maya',
            'child_name' => 'Yoga',
            'birthdate' => '2017-01-06 00:00:00',
            'gender' => 'l',
            'q1' => 'y',
            'q2' => 'y',
            'q3' => 't',
            'q4' => 'y',
            'q5' => Form2ImunizedReason::OP9,
            'q6' => 't',
            'q7' => ImunizedInformationSource::OP7,
            'q8' => 'y',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '2',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Rina',
            'child_name' => 'Yoga',
            'birthdate' => '2020-01-29 00:00:00',
            'gender' => 'l',
            'q1' => 't',
            'q2' => 't',
            'q3' => 'y',
            'q4' => 'y',
            'q5' => Form2ImunizedReason::OP4,
            'q6' => 'y',
            'q7' => ImunizedInformationSource::OP12,
            'q8' => 't',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '2',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Ayat',
            'child_name' => 'Nina',
            'birthdate' => '2017-01-31 00:00:00',
            'gender' => 'l',
            'q1' => 't',
            'q2' => 't',
            'q3' => 'y',
            'q4' => 'y',
            'q5' => Form2ImunizedReason::OP8,
            'q6' => 'y',
            'q7' => ImunizedInformationSource::OP12,
            'q8' => 'y',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '2',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Tono',
            'child_name' => 'Tari',
            'birthdate' => '2023-01-14 00:00:00',
            'gender' => 'p',
            'q1' => 't',
            'q2' => 'y',
            'q3' => 'y',
            'q4' => 't',
            'q5' => Form2ImunizedReason::OP3,
            'q6' => 't',
            'q7' => ImunizedInformationSource::OP2,
            'q8' => 'y',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '3',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Siti',
            'child_name' => 'Rio',
            'birthdate' => '2013-07-31 00:00:00',
            'gender' => 'p',
            'q1' => 't',
            'q2' => 't',
            'q3' => 'y',
            'q4' => 't',
            'q5' => Form2ImunizedReason::OP4,
            'q6' => 't',
            'q7' => ImunizedInformationSource::OP11,
            'q8' => 't',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '3',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Wati',
            'child_name' => 'Eka',
            'birthdate' => '2023-03-02 00:00:00',
            'gender' => 'l',
            'q1' => 'y',
            'q2' => 't',
            'q3' => 't',
            'q4' => 't',
            'q5' => Form2ImunizedReason::OP2,
            'q6' => 't',
            'q7' => ImunizedInformationSource::OP9,
            'q8' => 'y',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '3',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Rina',
            'child_name' => 'Eka',
            'birthdate' => '2021-03-08 00:00:00',
            'gender' => 'l',
            'q1' => 'y',
            'q2' => 't',
            'q3' => 'y',
            'q4' => 'y',
            'q5' => Form2ImunizedReason::OP5,
            'q6' => 't',
            'q7' => ImunizedInformationSource::OP10,
            'q8' => 'y',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '4',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Maya',
            'child_name' => 'Dina',
            'birthdate' => '2022-06-10 00:00:00',
            'gender' => 'p',
            'q1' => 'y',
            'q2' => 't',
            'q3' => 't',
            'q4' => 't',
            'q5' => Form2ImunizedReason::OP12,
            'q6' => 't',
            'q7' => ImunizedInformationSource::OP10,
            'q8' => 't',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '4',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Siti',
            'child_name' => 'Rio',
            'birthdate' => '2020-12-16 00:00:00',
            'gender' => 'p',
            'q1' => 'y',
            'q2' => 't',
            'q3' => 't',
            'q4' => 't',
            'q5' => Form2ImunizedReason::OP3,
            'q6' => 't',
            'q7' => ImunizedInformationSource::OP4,
            'q8' => 't',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '4',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Siti',
            'child_name' => 'Lala',
            'birthdate' => '2022-03-23 00:00:00',
            'gender' => 'p',
            'q1' => 't',
            'q2' => 'y',
            'q3' => 't',
            'q4' => 't',
            'q5' => Form2ImunizedReason::OP9,
            'q6' => 't',
            'q7' => ImunizedInformationSource::OP12,
            'q8' => 'y',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '5',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Rina',
            'child_name' => 'Tari',
            'birthdate' => '2021-04-19 00:00:00',
            'gender' => 'p',
            'q1' => 't',
            'q2' => 'y',
            'q3' => 'y',
            'q4' => 'y',
            'q5' => Form2ImunizedReason::OP8,
            'q6' => 'y',
            'q7' => ImunizedInformationSource::OP9,
            'q8' => 't',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '5',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Andi',
            'child_name' => 'Lala',
            'birthdate' => '2023-04-25 00:00:00',
            'gender' => 'p',
            'q1' => 't',
            'q2' => 't',
            'q3' => 't',
            'q4' => 't',
            'q5' => Form2ImunizedReason::OP5,
            'q6' => 't',
            'q7' => ImunizedInformationSource::OP12,
            'q8' => 'y',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '5',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Rina',
            'child_name' => 'Rio',
            'birthdate' => '2023-04-22 00:00:00',
            'gender' => 'l',
            'q1' => 'y',
            'q2' => 'y',
            'q3' => 'y',
            'q4' => 't',
            'q5' => Form2ImunizedReason::OP7,
            'q6' => 'y',
            'q7' => ImunizedInformationSource::OP11,
            'q8' => 'y',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '6',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Andi',
            'child_name' => 'Yoga',
            'birthdate' => '2012-09-17 00:00:00',
            'gender' => 'p',
            'q1' => 't',
            'q2' => 'y',
            'q3' => 't',
            'q4' => 't',
            'q5' => Form2ImunizedReason::OP2,
            'q6' => 't',
            'q7' => ImunizedInformationSource::OP3,
            'q8' => 't',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '6',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Wati',
            'child_name' => 'Nina',
            'birthdate' => '2018-05-25 00:00:00',
            'gender' => 'l',
            'q1' => 'y',
            'q2' => 'y',
            'q3' => 'y',
            'q4' => 't',
            'q5' => Form2ImunizedReason::OP10,
            'q6' => 'y',
            'q7' => ImunizedInformationSource::OP4,
            'q8' => 't',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '6',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Siti',
            'child_name' => 'Tari',
            'birthdate' => '2024-03-08 00:00:00',
            'gender' => 'p',
            'q1' => 't',
            'q2' => 't',
            'q3' => 'y',
            'q4' => 't',
            'q5' => Form2ImunizedReason::OP12,
            'q6' => 't',
            'q7' => ImunizedInformationSource::OP5,
            'q8' => 't',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '6',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Siti',
            'child_name' => 'Tari',
            'birthdate' => '2016-02-04 00:00:00',
            'gender' => 'l',
            'q1' => 't',
            'q2' => 'y',
            'q3' => 'y',
            'q4' => 't',
            'q5' => Form2ImunizedReason::OP1,
            'q6' => 't',
            'q7' => ImunizedInformationSource::OP5,
            'q8' => 't',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '7',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Rina',
            'child_name' => 'Dina',
            'birthdate' => '2011-04-22 00:00:00',
            'gender' => 'p',
            'q1' => 't',
            'q2' => 't',
            'q3' => 'y',
            'q4' => 'y',
            'q5' => Form2ImunizedReason::OP5,
            'q6' => 't',
            'q7' => ImunizedInformationSource::OP12,
            'q8' => 'y',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '7',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Maya',
            'child_name' => 'Salsa',
            'birthdate' => '2022-02-19 00:00:00',
            'gender' => 'p',
            'q1' => 'y',
            'q2' => 'y',
            'q3' => 'y',
            'q4' => 'y',
            'q5' => Form2ImunizedReason::OP10,
            'q6' => 't',
            'q7' => ImunizedInformationSource::OP2,
            'q8' => 't',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '7',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Wati',
            'child_name' => 'Lala',
            'birthdate' => '2015-02-17 00:00:00',
            'gender' => 'l',
            'q1' => 'y',
            'q2' => 'y',
            'q3' => 'y',
            'q4' => 't',
            'q5' => Form2ImunizedReason::OP2,
            'q6' => 't',
            'q7' => ImunizedInformationSource::OP9,
            'q8' => 'y',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '8',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Andi',
            'child_name' => 'Nina',
            'birthdate' => '2010-03-17 00:00:00',
            'gender' => 'l',
            'q1' => 'y',
            'q2' => 't',
            'q3' => 'y',
            'q4' => 'y',
            'q5' => Form2ImunizedReason::OP5,
            'q6' => 't',
            'q7' => ImunizedInformationSource::OP7,
            'q8' => 't',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '8',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Andi',
            'child_name' => 'Gilang',
            'birthdate' => '2014-11-15 00:00:00',
            'gender' => 'l',
            'q1' => 't',
            'q2' => 't',
            'q3' => 't',
            'q4' => 't',
            'q5' => Form2ImunizedReason::OP10,
            'q6' => 'y',
            'q7' => ImunizedInformationSource::OP3,
            'q8' => 'y',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '8',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Ayat',
            'child_name' => 'Raka',
            'birthdate' => '2015-01-22 00:00:00',
            'gender' => 'l',
            'q1' => 't',
            'q2' => 'y',
            'q3' => 'y',
            'q4' => 'y',
            'q5' => Form2ImunizedReason::OP1,
            'q6' => 't',
            'q7' => ImunizedInformationSource::OP12,
            'q8' => 't',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '8',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Maya',
            'child_name' => 'Yoga',
            'birthdate' => '2011-04-16 00:00:00',
            'gender' => 'p',
            'q1' => 'y',
            'q2' => 't',
            'q3' => 't',
            'q4' => 'y',
            'q5' => Form2ImunizedReason::OP10,
            'q6' => 'y',
            'q7' => ImunizedInformationSource::OP8,
            'q8' => 'y',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '9',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Rina',
            'child_name' => 'Tari',
            'birthdate' => '2023-11-23 00:00:00',
            'gender' => 'l',
            'q1' => 't',
            'q2' => 'y',
            'q3' => 'y',
            'q4' => 'y',
            'q5' => Form2ImunizedReason::OP1,
            'q6' => 't',
            'q7' => ImunizedInformationSource::OP12,
            'q8' => 'y',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '9',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Rina',
            'child_name' => 'Nina',
            'birthdate' => '2018-09-08 00:00:00',
            'gender' => 'p',
            'q1' => 't',
            'q2' => 'y',
            'q3' => 't',
            'q4' => 'y',
            'q5' => Form2ImunizedReason::OP5,
            'q6' => 'y',
            'q7' => ImunizedInformationSource::OP4,
            'q8' => 'y',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '9',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Budi',
            'child_name' => 'Lala',
            'birthdate' => '2012-10-31 00:00:00',
            'gender' => 'l',
            'q1' => 't',
            'q2' => 't',
            'q3' => 'y',
            'q4' => 't',
            'q5' => Form2ImunizedReason::OP1,
            'q6' => 'y',
            'q7' => ImunizedInformationSource::OP3,
            'q8' => 'y',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '10',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Ujang',
            'child_name' => 'Rio',
            'birthdate' => '2020-09-06 00:00:00',
            'gender' => 'p',
            'q1' => 't',
            'q2' => 't',
            'q3' => 'y',
            'q4' => 't',
            'q5' => Form2ImunizedReason::OP11,
            'q6' => 't',
            'q7' => ImunizedInformationSource::OP1,
            'q8' => 't',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '10',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Maya',
            'child_name' => 'Tari',
            'birthdate' => '2019-10-30 00:00:00',
            'gender' => 'l',
            'q1' => 'y',
            'q2' => 'y',
            'q3' => 't',
            'q4' => 'y',
            'q5' => Form2ImunizedReason::OP3,
            'q6' => 't',
            'q7' => ImunizedInformationSource::OP3,
            'q8' => 'y',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '10',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Siti',
            'child_name' => 'Raka',
            'birthdate' => '2021-01-19 00:00:00',
            'gender' => 'l',
            'q1' => 'y',
            'q2' => 't',
            'q3' => 'y',
            'q4' => 'y',
            'q5' => Form2ImunizedReason::OP1,
            'q6' => 't',
            'q7' => ImunizedInformationSource::OP3,
            'q8' => 'y',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '10',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Rina',
            'child_name' => 'Salsa',
            'birthdate' => '2020-04-12 00:00:00',
            'gender' => 'l',
            'q1' => 'y',
            'q2' => 't',
            'q3' => 'y',
            'q4' => 'y',
            'q5' => Form2ImunizedReason::OP3,
            'q6' => 't',
            'q7' => ImunizedInformationSource::OP8,
            'q8' => 't',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '11',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Rina',
            'child_name' => 'Lala',
            'birthdate' => '2019-08-31 00:00:00',
            'gender' => 'p',
            'q1' => 't',
            'q2' => 't',
            'q3' => 'y',
            'q4' => 'y',
            'q5' => Form2ImunizedReason::OP13,
            'q6' => 't',
            'q7' => ImunizedInformationSource::OP1,
            'q8' => 't',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '11',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Tono',
            'child_name' => 'Dina',
            'birthdate' => '2010-12-03 00:00:00',
            'gender' => 'l',
            'q1' => 't',
            'q2' => 't',
            'q3' => 't',
            'q4' => 'y',
            'q5' => Form2ImunizedReason::OP7,
            'q6' => 'y',
            'q7' => ImunizedInformationSource::OP6,
            'q8' => 'y',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '11',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Siti',
            'child_name' => 'Salsa',
            'birthdate' => '2023-04-05 00:00:00',
            'gender' => 'l',
            'q1' => 't',
            'q2' => 'y',
            'q3' => 'y',
            'q4' => 'y',
            'q5' => Form2ImunizedReason::OP7,
            'q6' => 'y',
            'q7' => ImunizedInformationSource::OP7,
            'q8' => 'y',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '11',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Ayat',
            'child_name' => 'Yoga',
            'birthdate' => '2021-12-19 00:00:00',
            'gender' => 'p',
            'q1' => 'y',
            'q2' => 't',
            'q3' => 't',
            'q4' => 'y',
            'q5' => Form2ImunizedReason::OP9,
            'q6' => 't',
            'q7' => ImunizedInformationSource::OP3,
            'q8' => 't',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '12',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Maya',
            'child_name' => 'Tari',
            'birthdate' => '2020-10-22 00:00:00',
            'gender' => 'l',
            'q1' => 'y',
            'q2' => 'y',
            'q3' => 't',
            'q4' => 'y',
            'q5' => Form2ImunizedReason::OP3,
            'q6' => 't',
            'q7' => ImunizedInformationSource::OP8,
            'q8' => 't',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '12',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Maya',
            'child_name' => 'Raka',
            'birthdate' => '2011-03-04 00:00:00',
            'gender' => 'p',
            'q1' => 'y',
            'q2' => 'y',
            'q3' => 't',
            'q4' => 'y',
            'q5' => Form2ImunizedReason::OP9,
            'q6' => 'y',
            'q7' => ImunizedInformationSource::OP2,
            'q8' => 'y',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '12',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Ayat',
            'child_name' => 'Salsa',
            'birthdate' => '2017-07-02 00:00:00',
            'gender' => 'p',
            'q1' => 't',
            'q2' => 'y',
            'q3' => 'y',
            'q4' => 'y',
            'q5' => Form2ImunizedReason::OP4,
            'q6' => 'y',
            'q7' => ImunizedInformationSource::OP7,
            'q8' => 'y',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '12',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Ujang',
            'child_name' => 'Raka',
            'birthdate' => '2010-07-27 00:00:00',
            'gender' => 'l',
            'q1' => 'y',
            'q2' => 'y',
            'q3' => 't',
            'q4' => 't',
            'q5' => Form2ImunizedReason::OP5,
            'q6' => 'y',
            'q7' => ImunizedInformationSource::OP12,
            'q8' => 't',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '13',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Tono',
            'child_name' => 'Yoga',
            'birthdate' => '2011-04-05 00:00:00',
            'gender' => 'p',
            'q1' => 'y',
            'q2' => 'y',
            'q3' => 't',
            'q4' => 'y',
            'q5' => Form2ImunizedReason::OP12,
            'q6' => 't',
            'q7' => ImunizedInformationSource::OP6,
            'q8' => 'y',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '13',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Ayat',
            'child_name' => 'Rio',
            'birthdate' => '2013-06-07 00:00:00',
            'gender' => 'l',
            'q1' => 'y',
            'q2' => 'y',
            'q3' => 't',
            'q4' => 'y',
            'q5' => Form2ImunizedReason::OP2,
            'q6' => 'y',
            'q7' => ImunizedInformationSource::OP8,
            'q8' => 'y',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '13',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Budi',
            'child_name' => 'Tari',
            'birthdate' => '2015-03-07 00:00:00',
            'gender' => 'l',
            'q1' => 't',
            'q2' => 'y',
            'q3' => 'y',
            'q4' => 't',
            'q5' => Form2ImunizedReason::OP12,
            'q6' => 'y',
            'q7' => ImunizedInformationSource::OP11,
            'q8' => 't',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '13',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Wati',
            'child_name' => 'Raka',
            'birthdate' => '2012-02-27 00:00:00',
            'gender' => 'p',
            'q1' => 'y',
            'q2' => 't',
            'q3' => 't',
            'q4' => 'y',
            'q5' => Form2ImunizedReason::OP9,
            'q6' => 'y',
            'q7' => ImunizedInformationSource::OP4,
            'q8' => 'y',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '14',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Siti',
            'child_name' => 'Gilang',
            'birthdate' => '2022-05-30 00:00:00',
            'gender' => 'p',
            'q1' => 't',
            'q2' => 't',
            'q3' => 't',
            'q4' => 'y',
            'q5' => Form2ImunizedReason::OP1,
            'q6' => 't',
            'q7' => ImunizedInformationSource::OP6,
            'q8' => 't',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '14',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Budi',
            'child_name' => 'Rio',
            'birthdate' => '2023-06-07 00:00:00',
            'gender' => 'p',
            'q1' => 'y',
            'q2' => 't',
            'q3' => 't',
            'q4' => 'y',
            'q5' => Form2ImunizedReason::OP13,
            'q6' => 'y',
            'q7' => ImunizedInformationSource::OP8,
            'q8' => 'y',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '14',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Tono',
            'child_name' => 'Dina',
            'birthdate' => '2018-08-19 00:00:00',
            'gender' => 'p',
            'q1' => 'y',
            'q2' => 'y',
            'q3' => 't',
            'q4' => 't',
            'q5' => Form2ImunizedReason::OP2,
            'q6' => 't',
            'q7' => ImunizedInformationSource::OP1,
            'q8' => 'y',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '15',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Ayat',
            'child_name' => 'Lala',
            'birthdate' => '2019-12-10 00:00:00',
            'gender' => 'p',
            'q1' => 'y',
            'q2' => 't',
            'q3' => 't',
            'q4' => 'y',
            'q5' => Form2ImunizedReason::OP7,
            'q6' => 'y',
            'q7' => ImunizedInformationSource::OP6,
            'q8' => 'y',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '15',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Wati',
            'child_name' => 'Nina',
            'birthdate' => '2012-12-22 00:00:00',
            'gender' => 'p',
            'q1' => 'y',
            'q2' => 'y',
            'q3' => 't',
            'q4' => 'y',
            'q5' => Form2ImunizedReason::OP13,
            'q6' => 'y',
            'q7' => ImunizedInformationSource::OP3,
            'q8' => 'y',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '15',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Maya',
            'child_name' => 'Eka',
            'birthdate' => '2009-08-30 00:00:00',
            'gender' => 'p',
            'q1' => 'y',
            'q2' => 'y',
            'q3' => 't',
            'q4' => 't',
            'q5' => Form2ImunizedReason::OP1,
            'q6' => 't',
            'q7' => ImunizedInformationSource::OP1,
            'q8' => 'y',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '16',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Maya',
            'child_name' => 'Gilang',
            'birthdate' => '2016-12-27 00:00:00',
            'gender' => 'l',
            'q1' => 't',
            'q2' => 'y',
            'q3' => 'y',
            'q4' => 't',
            'q5' => Form2ImunizedReason::OP7,
            'q6' => 'y',
            'q7' => ImunizedInformationSource::OP11,
            'q8' => 't',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '16',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Desi',
            'child_name' => 'Gilang',
            'birthdate' => '2024-01-05 00:00:00',
            'gender' => 'l',
            'q1' => 'y',
            'q2' => 't',
            'q3' => 't',
            'q4' => 'y',
            'q5' => Form2ImunizedReason::OP5,
            'q6' => 'y',
            'q7' => ImunizedInformationSource::OP12,
            'q8' => 't',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '16',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Budi',
            'child_name' => 'Lala',
            'birthdate' => '2015-05-19 00:00:00',
            'gender' => 'p',
            'q1' => 't',
            'q2' => 't',
            'q3' => 'y',
            'q4' => 't',
            'q5' => Form2ImunizedReason::OP8,
            'q6' => 'y',
            'q7' => ImunizedInformationSource::OP8,
            'q8' => 'y',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '17',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Maya',
            'child_name' => 'Rio',
            'birthdate' => '2012-03-22 00:00:00',
            'gender' => 'l',
            'q1' => 'y',
            'q2' => 't',
            'q3' => 'y',
            'q4' => 'y',
            'q5' => Form2ImunizedReason::OP11,
            'q6' => 't',
            'q7' => ImunizedInformationSource::OP3,
            'q8' => 'y',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '17',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Desi',
            'child_name' => 'Tari',
            'birthdate' => '2022-11-29 00:00:00',
            'gender' => 'p',
            'q1' => 'y',
            'q2' => 't',
            'q3' => 'y',
            'q4' => 't',
            'q5' => Form2ImunizedReason::OP12,
            'q6' => 't',
            'q7' => ImunizedInformationSource::OP2,
            'q8' => 't',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '17',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Tono',
            'child_name' => 'Lala',
            'birthdate' => '2022-04-19 00:00:00',
            'gender' => 'p',
            'q1' => 'y',
            'q2' => 'y',
            'q3' => 't',
            'q4' => 'y',
            'q5' => Form2ImunizedReason::OP11,
            'q6' => 't',
            'q7' => ImunizedInformationSource::OP10,
            'q8' => 't',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '17',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Budi',
            'child_name' => 'Yoga',
            'birthdate' => '2014-07-13 00:00:00',
            'gender' => 'p',
            'q1' => 't',
            'q2' => 't',
            'q3' => 'y',
            'q4' => 'y',
            'q5' => Form2ImunizedReason::OP7,
            'q6' => 'y',
            'q7' => ImunizedInformationSource::OP12,
            'q8' => 't',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '18',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Andi',
            'child_name' => 'Yoga',
            'birthdate' => '2013-04-12 00:00:00',
            'gender' => 'p',
            'q1' => 'y',
            'q2' => 'y',
            'q3' => 't',
            'q4' => 'y',
            'q5' => Form2ImunizedReason::OP7,
            'q6' => 'y',
            'q7' => ImunizedInformationSource::OP6,
            'q8' => 't',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '18',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Andi',
            'child_name' => 'Gilang',
            'birthdate' => '2012-09-28 00:00:00',
            'gender' => 'p',
            'q1' => 'y',
            'q2' => 'y',
            'q3' => 't',
            'q4' => 't',
            'q5' => Form2ImunizedReason::OP5,
            'q6' => 'y',
            'q7' => ImunizedInformationSource::OP3,
            'q8' => 't',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '18',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Desi',
            'child_name' => 'Nina',
            'birthdate' => '2010-10-24 00:00:00',
            'gender' => 'l',
            'q1' => 'y',
            'q2' => 't',
            'q3' => 't',
            'q4' => 't',
            'q5' => Form2ImunizedReason::OP3,
            'q6' => 'y',
            'q7' => ImunizedInformationSource::OP2,
            'q8' => 't',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '18',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Maya',
            'child_name' => 'Raka',
            'birthdate' => '2020-10-24 00:00:00',
            'gender' => 'p',
            'q1' => 'y',
            'q2' => 't',
            'q3' => 't',
            'q4' => 'y',
            'q5' => Form2ImunizedReason::OP13,
            'q6' => 'y',
            'q7' => ImunizedInformationSource::OP5,
            'q8' => 'y',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '19',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Siti',
            'child_name' => 'Eka',
            'birthdate' => '2017-06-19 00:00:00',
            'gender' => 'l',
            'q1' => 't',
            'q2' => 'y',
            'q3' => 't',
            'q4' => 't',
            'q5' => Form2ImunizedReason::OP1,
            'q6' => 'y',
            'q7' => ImunizedInformationSource::OP5,
            'q8' => 'y',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '19',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Siti',
            'child_name' => 'Gilang',
            'birthdate' => '2018-11-16 00:00:00',
            'gender' => 'p',
            'q1' => 'y',
            'q2' => 't',
            'q3' => 'y',
            'q4' => 't',
            'q5' => Form2ImunizedReason::OP7,
            'q6' => 'y',
            'q7' => ImunizedInformationSource::OP9,
            'q8' => 't',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '19',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Siti',
            'child_name' => 'Raka',
            'birthdate' => '2018-04-11 00:00:00',
            'gender' => 'p',
            'q1' => 'y',
            'q2' => 'y',
            'q3' => 't',
            'q4' => 't',
            'q5' => Form2ImunizedReason::OP2,
            'q6' => 't',
            'q7' => ImunizedInformationSource::OP9,
            'q8' => 'y',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '19',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Desi',
            'child_name' => 'Tari',
            'birthdate' => '2022-12-27 00:00:00',
            'gender' => 'l',
            'q1' => 'y',
            'q2' => 'y',
            'q3' => 'y',
            'q4' => 'y',
            'q5' => Form2ImunizedReason::OP3,
            'q6' => 'y',
            'q7' => ImunizedInformationSource::OP9,
            'q8' => 't',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '20',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Rina',
            'child_name' => 'Tari',
            'birthdate' => '2020-08-14 00:00:00',
            'gender' => 'l',
            'q1' => 'y',
            'q2' => 't',
            'q3' => 'y',
            'q4' => 'y',
            'q5' => Form2ImunizedReason::OP5,
            'q6' => 't',
            'q7' => ImunizedInformationSource::OP3,
            'q8' => 'y',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '20',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Andi',
            'child_name' => 'Lala',
            'birthdate' => '2017-03-04 00:00:00',
            'gender' => 'p',
            'q1' => 'y',
            'q2' => 't',
            'q3' => 't',
            'q4' => 't',
            'q5' => Form2ImunizedReason::OP3,
            'q6' => 't',
            'q7' => ImunizedInformationSource::OP6,
            'q8' => 'y',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '20',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Siti',
            'child_name' => 'Raka',
            'birthdate' => '2016-11-12 00:00:00',
            'gender' => 'l',
            'q1' => 'y',
            'q2' => 't',
            'q3' => 'y',
            'q4' => 't',
            'q5' => Form2ImunizedReason::OP7,
            'q6' => 'y',
            'q7' => ImunizedInformationSource::OP1,
            'q8' => 't',
            'q9' => null,
        ]);
        
        Form2Answer::create([
            'house_id' => '20',
            'kode_fasyankes' => '32760200001',
            'year' => '2025',
            'parent_name' => 'Ayat',
            'child_name' => 'Yoga',
            'birthdate' => '2022-10-20 00:00:00',
            'gender' => 'p',
            'q1' => 't',
            'q2' => 't',
            'q3' => 'y',
            'q4' => 't',
            'q5' => Form2ImunizedReason::OP2,
            'q6' => 't',
            'q7' => ImunizedInformationSource::OP7,
            'q8' => 'y',
            'q9' => null,
        ]);
        

    }
}
