<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Regency;

class RegencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $regencies = [

            // [ 'id' => '', 'regency_id' => '', 'province_id' => '', 'name' => '', ],

            [ 'id' => '1', 'regency_id' => '1101', 'province_id' => '11', 'name' => 'KAB. ACEH SELATAN', ],
            [ 'id' => '2', 'regency_id' => '1102', 'province_id' => '11', 'name' => 'KAB. ACEH TENGGARA', ],
            [ 'id' => '3', 'regency_id' => '1103', 'province_id' => '11', 'name' => 'KAB. ACEH TIMUR', ],
            [ 'id' => '4', 'regency_id' => '1104', 'province_id' => '11', 'name' => 'KAB. ACEH TENGAH', ],
            [ 'id' => '5', 'regency_id' => '1105', 'province_id' => '11', 'name' => 'KAB. ACEH BARAT', ],
            [ 'id' => '6', 'regency_id' => '1106', 'province_id' => '11', 'name' => 'KAB. ACEH BESAR', ],
            [ 'id' => '7', 'regency_id' => '1107', 'province_id' => '11', 'name' => 'KAB. PIDIE', ],
            [ 'id' => '8', 'regency_id' => '1108', 'province_id' => '11', 'name' => 'KAB. ACEH UTARA', ],
            [ 'id' => '9', 'regency_id' => '1109', 'province_id' => '11', 'name' => 'KAB. SIMEULUE', ],
            [ 'id' => '10', 'regency_id' => '1110', 'province_id' => '11', 'name' => 'KAB. ACEH SINGKIL', ],
            [ 'id' => '11', 'regency_id' => '1111', 'province_id' => '11', 'name' => 'KAB. BIREUEN', ],
            [ 'id' => '12', 'regency_id' => '1112', 'province_id' => '11', 'name' => 'KAB. ACEH BARAT DAYA', ],
            [ 'id' => '13', 'regency_id' => '1113', 'province_id' => '11', 'name' => 'KAB. GAYO LUES', ],
            [ 'id' => '14', 'regency_id' => '1114', 'province_id' => '11', 'name' => 'KAB. ACEH JAYA', ],
            [ 'id' => '15', 'regency_id' => '1115', 'province_id' => '11', 'name' => 'KAB. NAGAN RAYA', ],
            [ 'id' => '16', 'regency_id' => '1116', 'province_id' => '11', 'name' => 'KAB. ACEH TAMIANG', ],
            [ 'id' => '17', 'regency_id' => '1117', 'province_id' => '11', 'name' => 'KAB. BENER MERIAH', ],
            [ 'id' => '18', 'regency_id' => '1118', 'province_id' => '11', 'name' => 'KAB. PIDIE JAYA', ],
            [ 'id' => '19', 'regency_id' => '1171', 'province_id' => '11', 'name' => 'KOTA BANDA ACEH', ],
            [ 'id' => '20', 'regency_id' => '1172', 'province_id' => '11', 'name' => 'KOTA SABANG', ],
            [ 'id' => '21', 'regency_id' => '1173', 'province_id' => '11', 'name' => 'KOTA LHOKSEUMAWE', ],
            [ 'id' => '22', 'regency_id' => '1174', 'province_id' => '11', 'name' => 'KOTA LANGSA', ],
            [ 'id' => '23', 'regency_id' => '1175', 'province_id' => '11', 'name' => 'KOTA SUBULUSSALAM', ],
            [ 'id' => '24', 'regency_id' => '1201', 'province_id' => '12', 'name' => 'KAB. TAPANULI TENGAH', ],
            [ 'id' => '25', 'regency_id' => '1202', 'province_id' => '12', 'name' => 'KAB. TAPANULI UTARA', ],
            [ 'id' => '26', 'regency_id' => '1203', 'province_id' => '12', 'name' => 'KAB. TAPANULI SELATAN', ],
            [ 'id' => '27', 'regency_id' => '1204', 'province_id' => '12', 'name' => 'KAB. NIAS', ],
            [ 'id' => '28', 'regency_id' => '1205', 'province_id' => '12', 'name' => 'KAB. LANGKAT', ],
            [ 'id' => '29', 'regency_id' => '1206', 'province_id' => '12', 'name' => 'KAB. KARO', ],
            [ 'id' => '30', 'regency_id' => '1207', 'province_id' => '12', 'name' => 'KAB. DELI SERDANG', ],
            [ 'id' => '31', 'regency_id' => '1208', 'province_id' => '12', 'name' => 'KAB. SIMALUNGUN', ],
            [ 'id' => '32', 'regency_id' => '1209', 'province_id' => '12', 'name' => 'KAB. ASAHAN', ],
            [ 'id' => '33', 'regency_id' => '1210', 'province_id' => '12', 'name' => 'KAB. LABUHANBATU', ],
            [ 'id' => '34', 'regency_id' => '1211', 'province_id' => '12', 'name' => 'KAB. DAIRI', ],
            [ 'id' => '35', 'regency_id' => '1212', 'province_id' => '12', 'name' => 'KAB. TOBA', ],
            [ 'id' => '36', 'regency_id' => '1213', 'province_id' => '12', 'name' => 'KAB. MANDAILING NATAL', ],
            [ 'id' => '37', 'regency_id' => '1214', 'province_id' => '12', 'name' => 'KAB. NIAS SELATAN', ],
            [ 'id' => '38', 'regency_id' => '1215', 'province_id' => '12', 'name' => 'KAB. PAKPAK BHARAT', ],
            [ 'id' => '39', 'regency_id' => '1216', 'province_id' => '12', 'name' => 'KAB. HUMBANG HASUNDUTAN', ],
            [ 'id' => '40', 'regency_id' => '1217', 'province_id' => '12', 'name' => 'KAB. SAMOSIR', ],
            [ 'id' => '41', 'regency_id' => '1218', 'province_id' => '12', 'name' => 'KAB. SERDANG BEDAGAI', ],
            [ 'id' => '42', 'regency_id' => '1219', 'province_id' => '12', 'name' => 'KAB. BATU BARA', ],
            [ 'id' => '43', 'regency_id' => '1220', 'province_id' => '12', 'name' => 'KAB. PADANG LAWAS UTARA', ],
            [ 'id' => '44', 'regency_id' => '1221', 'province_id' => '12', 'name' => 'KAB. PADANG LAWAS', ],
            [ 'id' => '45', 'regency_id' => '1222', 'province_id' => '12', 'name' => 'KAB. LABUHANBATU SELATAN', ],
            [ 'id' => '46', 'regency_id' => '1223', 'province_id' => '12', 'name' => 'KAB. LABUHANBATU UTARA', ],
            [ 'id' => '47', 'regency_id' => '1224', 'province_id' => '12', 'name' => 'KAB. NIAS UTARA', ],
            [ 'id' => '48', 'regency_id' => '1225', 'province_id' => '12', 'name' => 'KAB. NIAS BARAT', ],
            [ 'id' => '49', 'regency_id' => '1271', 'province_id' => '12', 'name' => 'KOTA MEDAN', ],
            [ 'id' => '50', 'regency_id' => '1272', 'province_id' => '12', 'name' => 'KOTA PEMATANGSIANTAR', ],
            [ 'id' => '51', 'regency_id' => '1273', 'province_id' => '12', 'name' => 'KOTA SIBOLGA', ],
            [ 'id' => '52', 'regency_id' => '1274', 'province_id' => '12', 'name' => 'KOTA TANJUNG BALAI', ],
            [ 'id' => '53', 'regency_id' => '1275', 'province_id' => '12', 'name' => 'KOTA BINJAI', ],
            [ 'id' => '54', 'regency_id' => '1276', 'province_id' => '12', 'name' => 'KOTA TEBING TINGGI', ],
            [ 'id' => '55', 'regency_id' => '1277', 'province_id' => '12', 'name' => 'KOTA PADANG SIDEMPUAN', ],
            [ 'id' => '56', 'regency_id' => '1278', 'province_id' => '12', 'name' => 'KOTA GUNUNGSITOLI', ],
            [ 'id' => '57', 'regency_id' => '1301', 'province_id' => '13', 'name' => 'KAB. PESISIR SELATAN', ],
            [ 'id' => '58', 'regency_id' => '1302', 'province_id' => '13', 'name' => 'KAB. SOLOK', ],
            [ 'id' => '59', 'regency_id' => '1303', 'province_id' => '13', 'name' => 'KAB. SIJUNJUNG', ],
            [ 'id' => '60', 'regency_id' => '1304', 'province_id' => '13', 'name' => 'KAB. TANAH DATAR', ],
            [ 'id' => '61', 'regency_id' => '1305', 'province_id' => '13', 'name' => 'KAB. PADANG PARIAMAN', ],
            [ 'id' => '62', 'regency_id' => '1306', 'province_id' => '13', 'name' => 'KAB. AGAM', ],
            [ 'id' => '63', 'regency_id' => '1307', 'province_id' => '13', 'name' => 'KAB. LIMA PULUH KOTA', ],
            [ 'id' => '64', 'regency_id' => '1308', 'province_id' => '13', 'name' => 'KAB. PASAMAN', ],
            [ 'id' => '65', 'regency_id' => '1309', 'province_id' => '13', 'name' => 'KAB. KEPULAUAN MENTAWAI', ],
            [ 'id' => '66', 'regency_id' => '1310', 'province_id' => '13', 'name' => 'KAB. DHARMASRAYA', ],
            [ 'id' => '67', 'regency_id' => '1311', 'province_id' => '13', 'name' => 'KAB. SOLOK SELATAN', ],
            [ 'id' => '68', 'regency_id' => '1312', 'province_id' => '13', 'name' => 'KAB. PASAMAN BARAT', ],
            [ 'id' => '69', 'regency_id' => '1371', 'province_id' => '13', 'name' => 'KOTA PADANG', ],
            [ 'id' => '70', 'regency_id' => '1372', 'province_id' => '13', 'name' => 'KOTA SOLOK', ],
            [ 'id' => '71', 'regency_id' => '1373', 'province_id' => '13', 'name' => 'KOTA SAWAHLUNTO', ],
            [ 'id' => '72', 'regency_id' => '1374', 'province_id' => '13', 'name' => 'KOTA PADANG PANJANG', ],
            [ 'id' => '73', 'regency_id' => '1375', 'province_id' => '13', 'name' => 'KOTA BUKITTINGGI', ],
            [ 'id' => '74', 'regency_id' => '1376', 'province_id' => '13', 'name' => 'KOTA PAYAKUMBUH', ],
            [ 'id' => '75', 'regency_id' => '1377', 'province_id' => '13', 'name' => 'KOTA PARIAMAN', ],
            [ 'id' => '76', 'regency_id' => '1401', 'province_id' => '14', 'name' => 'KAB. KAMPAR', ],
            [ 'id' => '77', 'regency_id' => '1402', 'province_id' => '14', 'name' => 'KAB. INDRAGIRI HULU', ],
            [ 'id' => '78', 'regency_id' => '1403', 'province_id' => '14', 'name' => 'KAB. BENGKALIS', ],
            [ 'id' => '79', 'regency_id' => '1404', 'province_id' => '14', 'name' => 'KAB. INDRAGIRI HILIR', ],
            [ 'id' => '80', 'regency_id' => '1405', 'province_id' => '14', 'name' => 'KAB. PELALAWAN', ],
            [ 'id' => '81', 'regency_id' => '1406', 'province_id' => '14', 'name' => 'KAB. ROKAN HULU', ],
            [ 'id' => '82', 'regency_id' => '1407', 'province_id' => '14', 'name' => 'KAB. ROKAN HILIR', ],
            [ 'id' => '83', 'regency_id' => '1408', 'province_id' => '14', 'name' => 'KAB. SIAK', ],
            [ 'id' => '84', 'regency_id' => '1409', 'province_id' => '14', 'name' => 'KAB. KUANTAN SINGINGI', ],
            [ 'id' => '85', 'regency_id' => '1410', 'province_id' => '14', 'name' => 'KAB. KEPULAUAN MERANTI', ],
            [ 'id' => '86', 'regency_id' => '1471', 'province_id' => '14', 'name' => 'KOTA PEKANBARU', ],
            [ 'id' => '87', 'regency_id' => '1472', 'province_id' => '14', 'name' => 'KOTA DUMAI', ],
            [ 'id' => '88', 'regency_id' => '1501', 'province_id' => '15', 'name' => 'KAB. KERINCI', ],
            [ 'id' => '89', 'regency_id' => '1502', 'province_id' => '15', 'name' => 'KAB. MERANGIN', ],
            [ 'id' => '90', 'regency_id' => '1503', 'province_id' => '15', 'name' => 'KAB. SAROLANGUN', ],
            [ 'id' => '91', 'regency_id' => '1504', 'province_id' => '15', 'name' => 'KAB. BATANGHARI', ],
            [ 'id' => '92', 'regency_id' => '1505', 'province_id' => '15', 'name' => 'KAB. MUARO JAMBI', ],
            [ 'id' => '93', 'regency_id' => '1506', 'province_id' => '15', 'name' => 'KAB. TANJUNG JABUNG BARAT', ],
            [ 'id' => '94', 'regency_id' => '1507', 'province_id' => '15', 'name' => 'KAB. TANJUNG JABUNG TIMUR', ],
            [ 'id' => '95', 'regency_id' => '1508', 'province_id' => '15', 'name' => 'KAB. BUNGO', ],
            [ 'id' => '96', 'regency_id' => '1509', 'province_id' => '15', 'name' => 'KAB. TEBO', ],
            [ 'id' => '97', 'regency_id' => '1571', 'province_id' => '15', 'name' => 'KOTA JAMBI', ],
            [ 'id' => '98', 'regency_id' => '1572', 'province_id' => '15', 'name' => 'KOTA SUNGAI PENUH', ],
            [ 'id' => '99', 'regency_id' => '1601', 'province_id' => '16', 'name' => 'KAB. OGAN KOMERING ULU', ],
            [ 'id' => '100', 'regency_id' => '1602', 'province_id' => '16', 'name' => 'KAB. OGAN KOMERING ILIR', ],
            [ 'id' => '101', 'regency_id' => '1603', 'province_id' => '16', 'name' => 'KAB. MUARA ENIM', ],
            [ 'id' => '102', 'regency_id' => '1604', 'province_id' => '16', 'name' => 'KAB. LAHAT', ],
            [ 'id' => '103', 'regency_id' => '1605', 'province_id' => '16', 'name' => 'KAB. MUSI RAWAS', ],
            [ 'id' => '104', 'regency_id' => '1606', 'province_id' => '16', 'name' => 'KAB. MUSI BANYUASIN', ],
            [ 'id' => '105', 'regency_id' => '1607', 'province_id' => '16', 'name' => 'KAB. BANYUASIN', ],
            [ 'id' => '106', 'regency_id' => '1608', 'province_id' => '16', 'name' => 'KAB. OGAN KOMERING ULU TIMUR', ],
            [ 'id' => '107', 'regency_id' => '1609', 'province_id' => '16', 'name' => 'KAB. OGAN KOMERING ULU SELATAN', ],
            [ 'id' => '108', 'regency_id' => '1610', 'province_id' => '16', 'name' => 'KAB. OGAN ILIR', ],
            [ 'id' => '109', 'regency_id' => '1611', 'province_id' => '16', 'name' => 'KAB. EMPAT LAWANG', ],
            [ 'id' => '110', 'regency_id' => '1612', 'province_id' => '16', 'name' => 'KAB. PENUKAL ABAB LEMATANG ILIR', ],
            [ 'id' => '111', 'regency_id' => '1613', 'province_id' => '16', 'name' => 'KAB. MUSI RAWAS UTARA', ],
            [ 'id' => '112', 'regency_id' => '1671', 'province_id' => '16', 'name' => 'KOTA PALEMBANG', ],
            [ 'id' => '113', 'regency_id' => '1672', 'province_id' => '16', 'name' => 'KOTA PAGAR ALAM', ],
            [ 'id' => '114', 'regency_id' => '1673', 'province_id' => '16', 'name' => 'KOTA LUBUK LINGGAU', ],
            [ 'id' => '115', 'regency_id' => '1674', 'province_id' => '16', 'name' => 'KOTA PRABUMULIH', ],
            [ 'id' => '116', 'regency_id' => '1701', 'province_id' => '17', 'name' => 'KAB. BENGKULU SELATAN', ],
            [ 'id' => '117', 'regency_id' => '1702', 'province_id' => '17', 'name' => 'KAB. REJANG LEBONG', ],
            [ 'id' => '118', 'regency_id' => '1703', 'province_id' => '17', 'name' => 'KAB. BENGKULU UTARA', ],
            [ 'id' => '119', 'regency_id' => '1704', 'province_id' => '17', 'name' => 'KAB. KAUR', ],
            [ 'id' => '120', 'regency_id' => '1705', 'province_id' => '17', 'name' => 'KAB. SELUMA', ],
            [ 'id' => '121', 'regency_id' => '1706', 'province_id' => '17', 'name' => 'KAB. MUKO MUKO', ],
            [ 'id' => '122', 'regency_id' => '1707', 'province_id' => '17', 'name' => 'KAB. LEBONG', ],
            [ 'id' => '123', 'regency_id' => '1708', 'province_id' => '17', 'name' => 'KAB. KEPAHIANG', ],
            [ 'id' => '124', 'regency_id' => '1709', 'province_id' => '17', 'name' => 'KAB. BENGKULU TENGAH', ],
            [ 'id' => '125', 'regency_id' => '1771', 'province_id' => '17', 'name' => 'KOTA BENGKULU', ],
            [ 'id' => '126', 'regency_id' => '1801', 'province_id' => '18', 'name' => 'KAB. LAMPUNG SELATAN', ],
            [ 'id' => '127', 'regency_id' => '1802', 'province_id' => '18', 'name' => 'KAB. LAMPUNG TENGAH', ],
            [ 'id' => '128', 'regency_id' => '1803', 'province_id' => '18', 'name' => 'KAB. LAMPUNG UTARA', ],
            [ 'id' => '129', 'regency_id' => '1804', 'province_id' => '18', 'name' => 'KAB. LAMPUNG BARAT', ],
            [ 'id' => '130', 'regency_id' => '1805', 'province_id' => '18', 'name' => 'KAB. TULANG BAWANG', ],
            [ 'id' => '131', 'regency_id' => '1806', 'province_id' => '18', 'name' => 'KAB. TANGGAMUS', ],
            [ 'id' => '132', 'regency_id' => '1807', 'province_id' => '18', 'name' => 'KAB. LAMPUNG TIMUR', ],
            [ 'id' => '133', 'regency_id' => '1808', 'province_id' => '18', 'name' => 'KAB. WAY KANAN', ],
            [ 'id' => '134', 'regency_id' => '1809', 'province_id' => '18', 'name' => 'KAB. PESAWARAN', ],
            [ 'id' => '135', 'regency_id' => '1810', 'province_id' => '18', 'name' => 'KAB. PRINGSEWU', ],
            [ 'id' => '136', 'regency_id' => '1811', 'province_id' => '18', 'name' => 'KAB. MESUJI', ],
            [ 'id' => '137', 'regency_id' => '1812', 'province_id' => '18', 'name' => 'KAB. TULANG BAWANG BARAT', ],
            [ 'id' => '138', 'regency_id' => '1813', 'province_id' => '18', 'name' => 'KAB. PESISIR BARAT', ],
            [ 'id' => '139', 'regency_id' => '1871', 'province_id' => '18', 'name' => 'KOTA BANDAR LAMPUNG', ],
            [ 'id' => '140', 'regency_id' => '1872', 'province_id' => '18', 'name' => 'KOTA METRO', ],
            [ 'id' => '141', 'regency_id' => '1901', 'province_id' => '19', 'name' => 'KAB. BANGKA', ],
            [ 'id' => '142', 'regency_id' => '1902', 'province_id' => '19', 'name' => 'KAB. BELITUNG', ],
            [ 'id' => '143', 'regency_id' => '1903', 'province_id' => '19', 'name' => 'KAB. BANGKA SELATAN', ],
            [ 'id' => '144', 'regency_id' => '1904', 'province_id' => '19', 'name' => 'KAB. BANGKA TENGAH', ],
            [ 'id' => '145', 'regency_id' => '1905', 'province_id' => '19', 'name' => 'KAB. BANGKA BARAT', ],
            [ 'id' => '146', 'regency_id' => '1906', 'province_id' => '19', 'name' => 'KAB. BELITUNG TIMUR', ],
            [ 'id' => '147', 'regency_id' => '1971', 'province_id' => '19', 'name' => 'KOTA PANGKAL PINANG', ],
            [ 'id' => '148', 'regency_id' => '2101', 'province_id' => '21', 'name' => 'KAB. BINTAN', ],
            [ 'id' => '149', 'regency_id' => '2102', 'province_id' => '21', 'name' => 'KAB. KARIMUN', ],
            [ 'id' => '150', 'regency_id' => '2103', 'province_id' => '21', 'name' => 'KAB. NATUNA', ],
            [ 'id' => '151', 'regency_id' => '2104', 'province_id' => '21', 'name' => 'KAB. LINGGA', ],
            [ 'id' => '152', 'regency_id' => '2105', 'province_id' => '21', 'name' => 'KAB. KEPULAUAN ANAMBAS', ],
            [ 'id' => '153', 'regency_id' => '2171', 'province_id' => '21', 'name' => 'KOTA BATAM', ],
            [ 'id' => '154', 'regency_id' => '2172', 'province_id' => '21', 'name' => 'KOTA TANJUNG PINANG', ],
            [ 'id' => '155', 'regency_id' => '3101', 'province_id' => '31', 'name' => 'KAB. ADM. KEP. SERIBU', ],
            [ 'id' => '156', 'regency_id' => '3171', 'province_id' => '31', 'name' => 'KOTA ADM. JAKARTA PUSAT', ],
            [ 'id' => '157', 'regency_id' => '3172', 'province_id' => '31', 'name' => 'KOTA ADM. JAKARTA UTARA', ],
            [ 'id' => '158', 'regency_id' => '3173', 'province_id' => '31', 'name' => 'KOTA ADM. JAKARTA BARAT', ],
            [ 'id' => '159', 'regency_id' => '3174', 'province_id' => '31', 'name' => 'KOTA ADM. JAKARTA SELATAN', ],
            [ 'id' => '160', 'regency_id' => '3175', 'province_id' => '31', 'name' => 'KOTA ADM. JAKARTA TIMUR', ],
            [ 'id' => '161', 'regency_id' => '3201', 'province_id' => '32', 'name' => 'KAB. BOGOR', ],
            [ 'id' => '162', 'regency_id' => '3202', 'province_id' => '32', 'name' => 'KAB. SUKABUMI', ],
            [ 'id' => '163', 'regency_id' => '3203', 'province_id' => '32', 'name' => 'KAB. CIANJUR', ],
            [ 'id' => '164', 'regency_id' => '3204', 'province_id' => '32', 'name' => 'KAB. BANDUNG', ],
            [ 'id' => '165', 'regency_id' => '3205', 'province_id' => '32', 'name' => 'KAB. GARUT', ],
            [ 'id' => '166', 'regency_id' => '3206', 'province_id' => '32', 'name' => 'KAB. TASIKMALAYA', ],
            [ 'id' => '167', 'regency_id' => '3207', 'province_id' => '32', 'name' => 'KAB. CIAMIS', ],
            [ 'id' => '168', 'regency_id' => '3208', 'province_id' => '32', 'name' => 'KAB. KUNINGAN', ],
            [ 'id' => '169', 'regency_id' => '3209', 'province_id' => '32', 'name' => 'KAB. CIREBON', ],
            [ 'id' => '170', 'regency_id' => '3210', 'province_id' => '32', 'name' => 'KAB. MAJALENGKA', ],
            [ 'id' => '171', 'regency_id' => '3211', 'province_id' => '32', 'name' => 'KAB. SUMEDANG', ],
            [ 'id' => '172', 'regency_id' => '3212', 'province_id' => '32', 'name' => 'KAB. INDRAMAYU', ],
            [ 'id' => '173', 'regency_id' => '3213', 'province_id' => '32', 'name' => 'KAB. SUBANG', ],
            [ 'id' => '174', 'regency_id' => '3214', 'province_id' => '32', 'name' => 'KAB. PURWAKARTA', ],
            [ 'id' => '175', 'regency_id' => '3215', 'province_id' => '32', 'name' => 'KAB. KARAWANG', ],
            [ 'id' => '176', 'regency_id' => '3216', 'province_id' => '32', 'name' => 'KAB. BEKASI', ],
            [ 'id' => '177', 'regency_id' => '3217', 'province_id' => '32', 'name' => 'KAB. BANDUNG BARAT', ],
            [ 'id' => '178', 'regency_id' => '3218', 'province_id' => '32', 'name' => 'KAB. PANGANDARAN', ],
            [ 'id' => '179', 'regency_id' => '3271', 'province_id' => '32', 'name' => 'KOTA BOGOR', ],
            [ 'id' => '180', 'regency_id' => '3272', 'province_id' => '32', 'name' => 'KOTA SUKABUMI', ],
            [ 'id' => '181', 'regency_id' => '3273', 'province_id' => '32', 'name' => 'KOTA BANDUNG', ],
            [ 'id' => '182', 'regency_id' => '3274', 'province_id' => '32', 'name' => 'KOTA CIREBON', ],
            [ 'id' => '183', 'regency_id' => '3275', 'province_id' => '32', 'name' => 'KOTA BEKASI', ],
            [ 'id' => '184', 'regency_id' => '3276', 'province_id' => '32', 'name' => 'KOTA DEPOK', ],
            [ 'id' => '185', 'regency_id' => '3277', 'province_id' => '32', 'name' => 'KOTA CIMAHI', ],
            [ 'id' => '186', 'regency_id' => '3278', 'province_id' => '32', 'name' => 'KOTA TASIKMALAYA', ],
            [ 'id' => '187', 'regency_id' => '3279', 'province_id' => '32', 'name' => 'KOTA BANJAR', ],
            [ 'id' => '188', 'regency_id' => '3301', 'province_id' => '33', 'name' => 'KAB. CILACAP', ],
            [ 'id' => '189', 'regency_id' => '3302', 'province_id' => '33', 'name' => 'KAB. BANYUMAS', ],
            [ 'id' => '190', 'regency_id' => '3303', 'province_id' => '33', 'name' => 'KAB. PURBALINGGA', ],
            [ 'id' => '191', 'regency_id' => '3304', 'province_id' => '33', 'name' => 'KAB. BANJARNEGARA', ],
            [ 'id' => '192', 'regency_id' => '3305', 'province_id' => '33', 'name' => 'KAB. KEBUMEN', ],
            [ 'id' => '193', 'regency_id' => '3306', 'province_id' => '33', 'name' => 'KAB. PURWOREJO', ],
            [ 'id' => '194', 'regency_id' => '3307', 'province_id' => '33', 'name' => 'KAB. WONOSOBO', ],
            [ 'id' => '195', 'regency_id' => '3308', 'province_id' => '33', 'name' => 'KAB. MAGELANG', ],
            [ 'id' => '196', 'regency_id' => '3309', 'province_id' => '33', 'name' => 'KAB. BOYOLALI', ],
            [ 'id' => '197', 'regency_id' => '3310', 'province_id' => '33', 'name' => 'KAB. KLATEN', ],
            [ 'id' => '198', 'regency_id' => '3311', 'province_id' => '33', 'name' => 'KAB. SUKOHARJO', ],
            [ 'id' => '199', 'regency_id' => '3312', 'province_id' => '33', 'name' => 'KAB. WONOGIRI', ],
            [ 'id' => '200', 'regency_id' => '3313', 'province_id' => '33', 'name' => 'KAB. KARANGANYAR', ],
            [ 'id' => '201', 'regency_id' => '3314', 'province_id' => '33', 'name' => 'KAB. SRAGEN', ],
            [ 'id' => '202', 'regency_id' => '3315', 'province_id' => '33', 'name' => 'KAB. GROBOGAN', ],
            [ 'id' => '203', 'regency_id' => '3316', 'province_id' => '33', 'name' => 'KAB. BLORA', ],
            [ 'id' => '204', 'regency_id' => '3317', 'province_id' => '33', 'name' => 'KAB. REMBANG', ],
            [ 'id' => '205', 'regency_id' => '3318', 'province_id' => '33', 'name' => 'KAB. PATI', ],
            [ 'id' => '206', 'regency_id' => '3319', 'province_id' => '33', 'name' => 'KAB. KUDUS', ],
            [ 'id' => '207', 'regency_id' => '3320', 'province_id' => '33', 'name' => 'KAB. JEPARA', ],
            [ 'id' => '208', 'regency_id' => '3321', 'province_id' => '33', 'name' => 'KAB. DEMAK', ],
            [ 'id' => '209', 'regency_id' => '3322', 'province_id' => '33', 'name' => 'KAB. SEMARANG', ],
            [ 'id' => '210', 'regency_id' => '3323', 'province_id' => '33', 'name' => 'KAB. TEMANGGUNG', ],
            [ 'id' => '211', 'regency_id' => '3324', 'province_id' => '33', 'name' => 'KAB. KENDAL', ],
            [ 'id' => '212', 'regency_id' => '3325', 'province_id' => '33', 'name' => 'KAB. BATANG', ],
            [ 'id' => '213', 'regency_id' => '3326', 'province_id' => '33', 'name' => 'KAB. PEKALONGAN', ],
            [ 'id' => '214', 'regency_id' => '3327', 'province_id' => '33', 'name' => 'KAB. PEMALANG', ],
            [ 'id' => '215', 'regency_id' => '3328', 'province_id' => '33', 'name' => 'KAB. TEGAL', ],
            [ 'id' => '216', 'regency_id' => '3329', 'province_id' => '33', 'name' => 'KAB. BREBES', ],
            [ 'id' => '217', 'regency_id' => '3371', 'province_id' => '33', 'name' => 'KOTA MAGELANG', ],
            [ 'id' => '218', 'regency_id' => '3372', 'province_id' => '33', 'name' => 'KOTA SURAKARTA', ],
            [ 'id' => '219', 'regency_id' => '3373', 'province_id' => '33', 'name' => 'KOTA SALATIGA', ],
            [ 'id' => '220', 'regency_id' => '3374', 'province_id' => '33', 'name' => 'KOTA SEMARANG', ],
            [ 'id' => '221', 'regency_id' => '3375', 'province_id' => '33', 'name' => 'KOTA PEKALONGAN', ],
            [ 'id' => '222', 'regency_id' => '3376', 'province_id' => '33', 'name' => 'KOTA TEGAL', ],
            [ 'id' => '223', 'regency_id' => '3401', 'province_id' => '34', 'name' => 'KAB. KULON PROGO', ],
            [ 'id' => '224', 'regency_id' => '3402', 'province_id' => '34', 'name' => 'KAB. BANTUL', ],
            [ 'id' => '225', 'regency_id' => '3403', 'province_id' => '34', 'name' => 'KAB. GUNUNGKIDUL', ],
            [ 'id' => '226', 'regency_id' => '3404', 'province_id' => '34', 'name' => 'KAB. SLEMAN', ],
            [ 'id' => '227', 'regency_id' => '3471', 'province_id' => '34', 'name' => 'KOTA YOGYAKARTA', ],
            [ 'id' => '228', 'regency_id' => '3501', 'province_id' => '35', 'name' => 'KAB. PACITAN', ],
            [ 'id' => '229', 'regency_id' => '3502', 'province_id' => '35', 'name' => 'KAB. PONOROGO', ],
            [ 'id' => '230', 'regency_id' => '3503', 'province_id' => '35', 'name' => 'KAB. TRENGGALEK', ],
            [ 'id' => '231', 'regency_id' => '3504', 'province_id' => '35', 'name' => 'KAB. TULUNGAGUNG', ],
            [ 'id' => '232', 'regency_id' => '3505', 'province_id' => '35', 'name' => 'KAB. BLITAR', ],
            [ 'id' => '233', 'regency_id' => '3506', 'province_id' => '35', 'name' => 'KAB. KEDIRI', ],
            [ 'id' => '234', 'regency_id' => '3507', 'province_id' => '35', 'name' => 'KAB. MALANG', ],
            [ 'id' => '235', 'regency_id' => '3508', 'province_id' => '35', 'name' => 'KAB. LUMAJANG', ],
            [ 'id' => '236', 'regency_id' => '3509', 'province_id' => '35', 'name' => 'KAB. JEMBER', ],
            [ 'id' => '237', 'regency_id' => '3510', 'province_id' => '35', 'name' => 'KAB. BANYUWANGI', ],
            [ 'id' => '238', 'regency_id' => '3511', 'province_id' => '35', 'name' => 'KAB. BONDOWOSO', ],
            [ 'id' => '239', 'regency_id' => '3512', 'province_id' => '35', 'name' => 'KAB. SITUBONDO', ],
            [ 'id' => '240', 'regency_id' => '3513', 'province_id' => '35', 'name' => 'KAB. PROBOLINGGO', ],
            [ 'id' => '241', 'regency_id' => '3514', 'province_id' => '35', 'name' => 'KAB. PASURUAN', ],
            [ 'id' => '242', 'regency_id' => '3515', 'province_id' => '35', 'name' => 'KAB. SIDOARJO', ],
            [ 'id' => '243', 'regency_id' => '3516', 'province_id' => '35', 'name' => 'KAB. MOJOKERTO', ],
            [ 'id' => '244', 'regency_id' => '3517', 'province_id' => '35', 'name' => 'KAB. JOMBANG', ],
            [ 'id' => '245', 'regency_id' => '3518', 'province_id' => '35', 'name' => 'KAB. NGANJUK', ],
            [ 'id' => '246', 'regency_id' => '3519', 'province_id' => '35', 'name' => 'KAB. MADIUN', ],
            [ 'id' => '247', 'regency_id' => '3520', 'province_id' => '35', 'name' => 'KAB. MAGETAN', ],
            [ 'id' => '248', 'regency_id' => '3521', 'province_id' => '35', 'name' => 'KAB. NGAWI', ],
            [ 'id' => '249', 'regency_id' => '3522', 'province_id' => '35', 'name' => 'KAB. BOJONEGORO', ],
            [ 'id' => '250', 'regency_id' => '3523', 'province_id' => '35', 'name' => 'KAB. TUBAN', ],
            [ 'id' => '251', 'regency_id' => '3524', 'province_id' => '35', 'name' => 'KAB. LAMONGAN', ],
            [ 'id' => '252', 'regency_id' => '3525', 'province_id' => '35', 'name' => 'KAB. GRESIK', ],
            [ 'id' => '253', 'regency_id' => '3526', 'province_id' => '35', 'name' => 'KAB. BANGKALAN', ],
            [ 'id' => '254', 'regency_id' => '3527', 'province_id' => '35', 'name' => 'KAB. SAMPANG', ],
            [ 'id' => '255', 'regency_id' => '3528', 'province_id' => '35', 'name' => 'KAB. PAMEKASAN', ],
            [ 'id' => '256', 'regency_id' => '3529', 'province_id' => '35', 'name' => 'KAB. SUMENEP', ],
            [ 'id' => '257', 'regency_id' => '3571', 'province_id' => '35', 'name' => 'KOTA KEDIRI', ],
            [ 'id' => '258', 'regency_id' => '3572', 'province_id' => '35', 'name' => 'KOTA BLITAR', ],
            [ 'id' => '259', 'regency_id' => '3573', 'province_id' => '35', 'name' => 'KOTA MALANG', ],
            [ 'id' => '260', 'regency_id' => '3574', 'province_id' => '35', 'name' => 'KOTA PROBOLINGGO', ],
            [ 'id' => '261', 'regency_id' => '3575', 'province_id' => '35', 'name' => 'KOTA PASURUAN', ],
            [ 'id' => '262', 'regency_id' => '3576', 'province_id' => '35', 'name' => 'KOTA MOJOKERTO', ],
            [ 'id' => '263', 'regency_id' => '3577', 'province_id' => '35', 'name' => 'KOTA MADIUN', ],
            [ 'id' => '264', 'regency_id' => '3578', 'province_id' => '35', 'name' => 'KOTA SURABAYA', ],
            [ 'id' => '265', 'regency_id' => '3579', 'province_id' => '35', 'name' => 'KOTA BATU', ],
            [ 'id' => '266', 'regency_id' => '3601', 'province_id' => '36', 'name' => 'KAB. PANDEGLANG', ],
            [ 'id' => '267', 'regency_id' => '3602', 'province_id' => '36', 'name' => 'KAB. LEBAK', ],
            [ 'id' => '268', 'regency_id' => '3603', 'province_id' => '36', 'name' => 'KAB. TANGERANG', ],
            [ 'id' => '269', 'regency_id' => '3604', 'province_id' => '36', 'name' => 'KAB. SERANG', ],
            [ 'id' => '270', 'regency_id' => '3671', 'province_id' => '36', 'name' => 'KOTA TANGERANG', ],
            [ 'id' => '271', 'regency_id' => '3672', 'province_id' => '36', 'name' => 'KOTA CILEGON', ],
            [ 'id' => '272', 'regency_id' => '3673', 'province_id' => '36', 'name' => 'KOTA SERANG', ],
            [ 'id' => '273', 'regency_id' => '3674', 'province_id' => '36', 'name' => 'KOTA TANGERANG SELATAN', ],
            [ 'id' => '274', 'regency_id' => '5101', 'province_id' => '51', 'name' => 'KAB. JEMBRANA', ],
            [ 'id' => '275', 'regency_id' => '5102', 'province_id' => '51', 'name' => 'KAB. TABANAN', ],
            [ 'id' => '276', 'regency_id' => '5103', 'province_id' => '51', 'name' => 'KAB. BADUNG', ],
            [ 'id' => '277', 'regency_id' => '5104', 'province_id' => '51', 'name' => 'KAB. GIANYAR', ],
            [ 'id' => '278', 'regency_id' => '5105', 'province_id' => '51', 'name' => 'KAB. KLUNGKUNG', ],
            [ 'id' => '279', 'regency_id' => '5106', 'province_id' => '51', 'name' => 'KAB. BANGLI', ],
            [ 'id' => '280', 'regency_id' => '5107', 'province_id' => '51', 'name' => 'KAB. KARANGASEM', ],
            [ 'id' => '281', 'regency_id' => '5108', 'province_id' => '51', 'name' => 'KAB. BULELENG', ],
            [ 'id' => '282', 'regency_id' => '5171', 'province_id' => '51', 'name' => 'KOTA DENPASAR', ],
            [ 'id' => '283', 'regency_id' => '5201', 'province_id' => '52', 'name' => 'KAB. LOMBOK BARAT', ],
            [ 'id' => '284', 'regency_id' => '5202', 'province_id' => '52', 'name' => 'KAB. LOMBOK TENGAH', ],
            [ 'id' => '285', 'regency_id' => '5203', 'province_id' => '52', 'name' => 'KAB. LOMBOK TIMUR', ],
            [ 'id' => '286', 'regency_id' => '5204', 'province_id' => '52', 'name' => 'KAB. SUMBAWA', ],
            [ 'id' => '287', 'regency_id' => '5205', 'province_id' => '52', 'name' => 'KAB. DOMPU', ],
            [ 'id' => '288', 'regency_id' => '5206', 'province_id' => '52', 'name' => 'KAB. BIMA', ],
            [ 'id' => '289', 'regency_id' => '5207', 'province_id' => '52', 'name' => 'KAB. SUMBAWA BARAT', ],
            [ 'id' => '290', 'regency_id' => '5208', 'province_id' => '52', 'name' => 'KAB. LOMBOK UTARA', ],
            [ 'id' => '291', 'regency_id' => '5271', 'province_id' => '52', 'name' => 'KOTA MATARAM', ],
            [ 'id' => '292', 'regency_id' => '5272', 'province_id' => '52', 'name' => 'KOTA BIMA', ],
            [ 'id' => '293', 'regency_id' => '5301', 'province_id' => '53', 'name' => 'KAB. KUPANG', ],
            [ 'id' => '294', 'regency_id' => '5302', 'province_id' => '53', 'name' => 'KAB TIMOR TENGAH SELATAN', ],
            [ 'id' => '295', 'regency_id' => '5303', 'province_id' => '53', 'name' => 'KAB. TIMOR TENGAH UTARA', ],
            [ 'id' => '296', 'regency_id' => '5304', 'province_id' => '53', 'name' => 'KAB. BELU', ],
            [ 'id' => '297', 'regency_id' => '5305', 'province_id' => '53', 'name' => 'KAB. ALOR', ],
            [ 'id' => '298', 'regency_id' => '5306', 'province_id' => '53', 'name' => 'KAB. FLORES TIMUR', ],
            [ 'id' => '299', 'regency_id' => '5307', 'province_id' => '53', 'name' => 'KAB. SIKKA', ],
            [ 'id' => '300', 'regency_id' => '5308', 'province_id' => '53', 'name' => 'KAB. ENDE', ],
            [ 'id' => '301', 'regency_id' => '5309', 'province_id' => '53', 'name' => 'KAB. NGADA', ],
            [ 'id' => '302', 'regency_id' => '5310', 'province_id' => '53', 'name' => 'KAB. MANGGARAI', ],
            [ 'id' => '303', 'regency_id' => '5311', 'province_id' => '53', 'name' => 'KAB. SUMBA TIMUR', ],
            [ 'id' => '304', 'regency_id' => '5312', 'province_id' => '53', 'name' => 'KAB. SUMBA BARAT', ],
            [ 'id' => '305', 'regency_id' => '5313', 'province_id' => '53', 'name' => 'KAB. LEMBATA', ],
            [ 'id' => '306', 'regency_id' => '5314', 'province_id' => '53', 'name' => 'KAB. ROTE NDAO', ],
            [ 'id' => '307', 'regency_id' => '5315', 'province_id' => '53', 'name' => 'KAB. MANGGARAI BARAT', ],
            [ 'id' => '308', 'regency_id' => '5316', 'province_id' => '53', 'name' => 'KAB. NAGEKEO', ],
            [ 'id' => '309', 'regency_id' => '5317', 'province_id' => '53', 'name' => 'KAB. SUMBA TENGAH', ],
            [ 'id' => '310', 'regency_id' => '5318', 'province_id' => '53', 'name' => 'KAB. SUMBA BARAT DAYA', ],
            [ 'id' => '311', 'regency_id' => '5319', 'province_id' => '53', 'name' => 'KAB. MANGGARAI TIMUR', ],
            [ 'id' => '312', 'regency_id' => '5320', 'province_id' => '53', 'name' => 'KAB. SABU RAIJUA', ],
            [ 'id' => '313', 'regency_id' => '5321', 'province_id' => '53', 'name' => 'KAB. MALAKA', ],
            [ 'id' => '314', 'regency_id' => '5371', 'province_id' => '53', 'name' => 'KOTA KUPANG', ],
            [ 'id' => '315', 'regency_id' => '6101', 'province_id' => '61', 'name' => 'KAB. SAMBAS', ],
            [ 'id' => '316', 'regency_id' => '6102', 'province_id' => '61', 'name' => 'KAB. MEMPAWAH', ],
            [ 'id' => '317', 'regency_id' => '6103', 'province_id' => '61', 'name' => 'KAB. SANGGAU', ],
            [ 'id' => '318', 'regency_id' => '6104', 'province_id' => '61', 'name' => 'KAB. KETAPANG', ],
            [ 'id' => '319', 'regency_id' => '6105', 'province_id' => '61', 'name' => 'KAB. SINTANG', ],
            [ 'id' => '320', 'regency_id' => '6106', 'province_id' => '61', 'name' => 'KAB. KAPUAS HULU', ],
            [ 'id' => '321', 'regency_id' => '6107', 'province_id' => '61', 'name' => 'KAB. BENGKAYANG', ],
            [ 'id' => '322', 'regency_id' => '6108', 'province_id' => '61', 'name' => 'KAB. LANDAK', ],
            [ 'id' => '323', 'regency_id' => '6109', 'province_id' => '61', 'name' => 'KAB. SEKADAU', ],
            [ 'id' => '324', 'regency_id' => '6110', 'province_id' => '61', 'name' => 'KAB. MELAWI', ],
            [ 'id' => '325', 'regency_id' => '6111', 'province_id' => '61', 'name' => 'KAB. KAYONG UTARA', ],
            [ 'id' => '326', 'regency_id' => '6112', 'province_id' => '61', 'name' => 'KAB. KUBU RAYA', ],
            [ 'id' => '327', 'regency_id' => '6171', 'province_id' => '61', 'name' => 'KOTA PONTIANAK', ],
            [ 'id' => '328', 'regency_id' => '6172', 'province_id' => '61', 'name' => 'KOTA SINGKAWANG', ],
            [ 'id' => '329', 'regency_id' => '6201', 'province_id' => '62', 'name' => 'KAB. KOTAWARINGIN BARAT', ],
            [ 'id' => '330', 'regency_id' => '6202', 'province_id' => '62', 'name' => 'KAB. KOTAWARINGIN TIMUR', ],
            [ 'id' => '331', 'regency_id' => '6203', 'province_id' => '62', 'name' => 'KAB. KAPUAS', ],
            [ 'id' => '332', 'regency_id' => '6204', 'province_id' => '62', 'name' => 'KAB. BARITO SELATAN', ],
            [ 'id' => '333', 'regency_id' => '6205', 'province_id' => '62', 'name' => 'KAB. BARITO UTARA', ],
            [ 'id' => '334', 'regency_id' => '6206', 'province_id' => '62', 'name' => 'KAB. KATINGAN', ],
            [ 'id' => '335', 'regency_id' => '6207', 'province_id' => '62', 'name' => 'KAB. SERUYAN', ],
            [ 'id' => '336', 'regency_id' => '6208', 'province_id' => '62', 'name' => 'KAB. SUKAMARA', ],
            [ 'id' => '337', 'regency_id' => '6209', 'province_id' => '62', 'name' => 'KAB. LAMANDAU', ],
            [ 'id' => '338', 'regency_id' => '6210', 'province_id' => '62', 'name' => 'KAB. GUNUNG MAS', ],
            [ 'id' => '339', 'regency_id' => '6211', 'province_id' => '62', 'name' => 'KAB. PULANG PISAU', ],
            [ 'id' => '340', 'regency_id' => '6212', 'province_id' => '62', 'name' => 'KAB. MURUNG RAYA', ],
            [ 'id' => '341', 'regency_id' => '6213', 'province_id' => '62', 'name' => 'KAB. BARITO TIMUR', ],
            [ 'id' => '342', 'regency_id' => '6271', 'province_id' => '62', 'name' => 'KOTA PALANGKARAYA', ],
            [ 'id' => '343', 'regency_id' => '6301', 'province_id' => '63', 'name' => 'KAB. TANAH LAUT', ],
            [ 'id' => '344', 'regency_id' => '6302', 'province_id' => '63', 'name' => 'KAB. KOTABARU', ],
            [ 'id' => '345', 'regency_id' => '6303', 'province_id' => '63', 'name' => 'KAB. BANJAR', ],
            [ 'id' => '346', 'regency_id' => '6304', 'province_id' => '63', 'name' => 'KAB. BARITO KUALA', ],
            [ 'id' => '347', 'regency_id' => '6305', 'province_id' => '63', 'name' => 'KAB. TAPIN', ],
            [ 'id' => '348', 'regency_id' => '6306', 'province_id' => '63', 'name' => 'KAB. HULU SUNGAI SELATAN', ],
            [ 'id' => '349', 'regency_id' => '6307', 'province_id' => '63', 'name' => 'KAB. HULU SUNGAI TENGAH', ],
            [ 'id' => '350', 'regency_id' => '6308', 'province_id' => '63', 'name' => 'KAB. HULU SUNGAI UTARA', ],
            [ 'id' => '351', 'regency_id' => '6309', 'province_id' => '63', 'name' => 'KAB. TABALONG', ],
            [ 'id' => '352', 'regency_id' => '6310', 'province_id' => '63', 'name' => 'KAB. TANAH BUMBU', ],
            [ 'id' => '353', 'regency_id' => '6311', 'province_id' => '63', 'name' => 'KAB. BALANGAN', ],
            [ 'id' => '354', 'regency_id' => '6371', 'province_id' => '63', 'name' => 'KOTA BANJARMASIN', ],
            [ 'id' => '355', 'regency_id' => '6372', 'province_id' => '63', 'name' => 'KOTA BANJARBARU', ],
            [ 'id' => '356', 'regency_id' => '6401', 'province_id' => '64', 'name' => 'KAB. PASER', ],
            [ 'id' => '357', 'regency_id' => '6402', 'province_id' => '64', 'name' => 'KAB. KUTAI KARTANEGARA', ],
            [ 'id' => '358', 'regency_id' => '6403', 'province_id' => '64', 'name' => 'KAB. BERAU', ],
            [ 'id' => '359', 'regency_id' => '6407', 'province_id' => '64', 'name' => 'KAB. KUTAI BARAT', ],
            [ 'id' => '360', 'regency_id' => '6408', 'province_id' => '64', 'name' => 'KAB. KUTAI TIMUR', ],
            [ 'id' => '361', 'regency_id' => '6409', 'province_id' => '64', 'name' => 'KAB. PENAJAM PASER UTARA', ],
            [ 'id' => '362', 'regency_id' => '6411', 'province_id' => '64', 'name' => 'KAB. MAHAKAM ULU', ],
            [ 'id' => '363', 'regency_id' => '6471', 'province_id' => '64', 'name' => 'KOTA BALIKPAPAN', ],
            [ 'id' => '364', 'regency_id' => '6472', 'province_id' => '64', 'name' => 'KOTA SAMARINDA', ],
            [ 'id' => '365', 'regency_id' => '6474', 'province_id' => '64', 'name' => 'KOTA BONTANG', ],
            [ 'id' => '366', 'regency_id' => '6501', 'province_id' => '65', 'name' => 'KAB. BULUNGAN', ],
            [ 'id' => '367', 'regency_id' => '6502', 'province_id' => '65', 'name' => 'KAB. MALINAU', ],
            [ 'id' => '368', 'regency_id' => '6503', 'province_id' => '65', 'name' => 'KAB. NUNUKAN', ],
            [ 'id' => '369', 'regency_id' => '6504', 'province_id' => '65', 'name' => 'KAB. TANA TIDUNG', ],
            [ 'id' => '370', 'regency_id' => '6571', 'province_id' => '65', 'name' => 'KOTA TARAKAN', ],
            [ 'id' => '371', 'regency_id' => '7101', 'province_id' => '71', 'name' => 'KAB. BOLAANG MONGONDOW', ],
            [ 'id' => '372', 'regency_id' => '7102', 'province_id' => '71', 'name' => 'KAB. MINAHASA', ],
            [ 'id' => '373', 'regency_id' => '7103', 'province_id' => '71', 'name' => 'KAB. KEPULAUAN SANGIHE', ],
            [ 'id' => '374', 'regency_id' => '7104', 'province_id' => '71', 'name' => 'KAB. KEPULAUAN TALAUD', ],
            [ 'id' => '375', 'regency_id' => '7105', 'province_id' => '71', 'name' => 'KAB. MINAHASA SELATAN', ],
            [ 'id' => '376', 'regency_id' => '7106', 'province_id' => '71', 'name' => 'KAB. MINAHASA UTARA', ],
            [ 'id' => '377', 'regency_id' => '7107', 'province_id' => '71', 'name' => 'KAB. MINAHASA TENGGARA', ],
            [ 'id' => '378', 'regency_id' => '7108', 'province_id' => '71', 'name' => 'KAB. BOLAANG MONGONDOW UTARA', ],
            [ 'id' => '379', 'regency_id' => '7109', 'province_id' => '71', 'name' => 'KAB. KEP. SIAU TAGULANDANG BIARO', ],
            [ 'id' => '380', 'regency_id' => '7110', 'province_id' => '71', 'name' => 'KAB. BOLAANG MONGONDOW TIMUR', ],
            [ 'id' => '381', 'regency_id' => '7111', 'province_id' => '71', 'name' => 'KAB. BOLAANG MONGONDOW SELATAN', ],
            [ 'id' => '382', 'regency_id' => '7171', 'province_id' => '71', 'name' => 'KOTA MANADO', ],
            [ 'id' => '383', 'regency_id' => '7172', 'province_id' => '71', 'name' => 'KOTA BITUNG', ],
            [ 'id' => '384', 'regency_id' => '7173', 'province_id' => '71', 'name' => 'KOTA TOMOHON', ],
            [ 'id' => '385', 'regency_id' => '7174', 'province_id' => '71', 'name' => 'KOTA KOTAMOBAGU', ],
            [ 'id' => '386', 'regency_id' => '7201', 'province_id' => '72', 'name' => 'KAB. BANGGAI', ],
            [ 'id' => '387', 'regency_id' => '7202', 'province_id' => '72', 'name' => 'KAB. POSO', ],
            [ 'id' => '388', 'regency_id' => '7203', 'province_id' => '72', 'name' => 'KAB. DONGGALA', ],
            [ 'id' => '389', 'regency_id' => '7204', 'province_id' => '72', 'name' => 'KAB. TOLI TOLI', ],
            [ 'id' => '390', 'regency_id' => '7205', 'province_id' => '72', 'name' => 'KAB. BUOL', ],
            [ 'id' => '391', 'regency_id' => '7206', 'province_id' => '72', 'name' => 'KAB. MOROWALI', ],
            [ 'id' => '392', 'regency_id' => '7207', 'province_id' => '72', 'name' => 'KAB. BANGGAI KEPULAUAN', ],
            [ 'id' => '393', 'regency_id' => '7208', 'province_id' => '72', 'name' => 'KAB. PARIGI MOUTONG', ],
            [ 'id' => '394', 'regency_id' => '7209', 'province_id' => '72', 'name' => 'KAB. TOJO UNA UNA', ],
            [ 'id' => '395', 'regency_id' => '7210', 'province_id' => '72', 'name' => 'KAB. SIGI', ],
            [ 'id' => '396', 'regency_id' => '7211', 'province_id' => '72', 'name' => 'KAB. BANGGAI LAUT', ],
            [ 'id' => '397', 'regency_id' => '7212', 'province_id' => '72', 'name' => 'KAB. MOROWALI UTARA', ],
            [ 'id' => '398', 'regency_id' => '7271', 'province_id' => '72', 'name' => 'KOTA PALU', ],
            [ 'id' => '399', 'regency_id' => '7301', 'province_id' => '73', 'name' => 'KAB. KEPULAUAN SELAYAR', ],
            [ 'id' => '400', 'regency_id' => '7302', 'province_id' => '73', 'name' => 'KAB. BULUKUMBA', ],
            [ 'id' => '401', 'regency_id' => '7303', 'province_id' => '73', 'name' => 'KAB. BANTAENG', ],
            [ 'id' => '402', 'regency_id' => '7304', 'province_id' => '73', 'name' => 'KAB. JENEPONTO', ],
            [ 'id' => '403', 'regency_id' => '7305', 'province_id' => '73', 'name' => 'KAB. TAKALAR', ],
            [ 'id' => '404', 'regency_id' => '7306', 'province_id' => '73', 'name' => 'KAB. GOWA', ],
            [ 'id' => '405', 'regency_id' => '7307', 'province_id' => '73', 'name' => 'KAB. SINJAI', ],
            [ 'id' => '406', 'regency_id' => '7308', 'province_id' => '73', 'name' => 'KAB. BONE', ],
            [ 'id' => '407', 'regency_id' => '7309', 'province_id' => '73', 'name' => 'KAB. MAROS', ],
            [ 'id' => '408', 'regency_id' => '7310', 'province_id' => '73', 'name' => 'KAB. PANGKAJENE DAN KEPULAUAN', ],
            [ 'id' => '409', 'regency_id' => '7311', 'province_id' => '73', 'name' => 'KAB. BARRU', ],
            [ 'id' => '410', 'regency_id' => '7312', 'province_id' => '73', 'name' => 'KAB. SOPPENG', ],
            [ 'id' => '411', 'regency_id' => '7313', 'province_id' => '73', 'name' => 'KAB. WAJO', ],
            [ 'id' => '412', 'regency_id' => '7314', 'province_id' => '73', 'name' => 'KAB. SIDENRENG RAPPANG', ],
            [ 'id' => '413', 'regency_id' => '7315', 'province_id' => '73', 'name' => 'KAB. PINRANG', ],
            [ 'id' => '414', 'regency_id' => '7316', 'province_id' => '73', 'name' => 'KAB. ENREKANG', ],
            [ 'id' => '415', 'regency_id' => '7317', 'province_id' => '73', 'name' => 'KAB. LUWU', ],
            [ 'id' => '416', 'regency_id' => '7318', 'province_id' => '73', 'name' => 'KAB. TANA TORAJA', ],
            [ 'id' => '417', 'regency_id' => '7322', 'province_id' => '73', 'name' => 'KAB. LUWU UTARA', ],
            [ 'id' => '418', 'regency_id' => '7324', 'province_id' => '73', 'name' => 'KAB. LUWU TIMUR', ],
            [ 'id' => '419', 'regency_id' => '7326', 'province_id' => '73', 'name' => 'KAB. TORAJA UTARA', ],
            [ 'id' => '420', 'regency_id' => '7371', 'province_id' => '73', 'name' => 'KOTA MAKASSAR', ],
            [ 'id' => '421', 'regency_id' => '7372', 'province_id' => '73', 'name' => 'KOTA PAREPARE', ],
            [ 'id' => '422', 'regency_id' => '7373', 'province_id' => '73', 'name' => 'KOTA PALOPO', ],
            [ 'id' => '423', 'regency_id' => '7401', 'province_id' => '74', 'name' => 'KAB. KOLAKA', ],
            [ 'id' => '424', 'regency_id' => '7402', 'province_id' => '74', 'name' => 'KAB. KONAWE', ],
            [ 'id' => '425', 'regency_id' => '7403', 'province_id' => '74', 'name' => 'KAB. MUNA', ],
            [ 'id' => '426', 'regency_id' => '7404', 'province_id' => '74', 'name' => 'KAB. BUTON', ],
            [ 'id' => '427', 'regency_id' => '7405', 'province_id' => '74', 'name' => 'KAB. KONAWE SELATAN', ],
            [ 'id' => '428', 'regency_id' => '7406', 'province_id' => '74', 'name' => 'KAB. BOMBANA', ],
            [ 'id' => '429', 'regency_id' => '7407', 'province_id' => '74', 'name' => 'KAB. WAKATOBI', ],
            [ 'id' => '430', 'regency_id' => '7408', 'province_id' => '74', 'name' => 'KAB. KOLAKA UTARA', ],
            [ 'id' => '431', 'regency_id' => '7409', 'province_id' => '74', 'name' => 'KAB. KONAWE UTARA', ],
            [ 'id' => '432', 'regency_id' => '7410', 'province_id' => '74', 'name' => 'KAB. BUTON UTARA', ],
            [ 'id' => '433', 'regency_id' => '7411', 'province_id' => '74', 'name' => 'KAB. KOLAKA TIMUR', ],
            [ 'id' => '434', 'regency_id' => '7412', 'province_id' => '74', 'name' => 'KAB. KONAWE KEPULAUAN', ],
            [ 'id' => '435', 'regency_id' => '7413', 'province_id' => '74', 'name' => 'KAB. MUNA BARAT', ],
            [ 'id' => '436', 'regency_id' => '7414', 'province_id' => '74', 'name' => 'KAB. BUTON TENGAH', ],
            [ 'id' => '437', 'regency_id' => '7415', 'province_id' => '74', 'name' => 'KAB. BUTON SELATAN', ],
            [ 'id' => '438', 'regency_id' => '7471', 'province_id' => '74', 'name' => 'KOTA KENDARI', ],
            [ 'id' => '439', 'regency_id' => '7472', 'province_id' => '74', 'name' => 'KOTA BAU BAU', ],
            [ 'id' => '440', 'regency_id' => '7501', 'province_id' => '75', 'name' => 'KAB. GORONTALO', ],
            [ 'id' => '441', 'regency_id' => '7502', 'province_id' => '75', 'name' => 'KAB. BOALEMO', ],
            [ 'id' => '442', 'regency_id' => '7503', 'province_id' => '75', 'name' => 'KAB. BONE BOLANGO', ],
            [ 'id' => '443', 'regency_id' => '7504', 'province_id' => '75', 'name' => 'KAB. POHUWATO', ],
            [ 'id' => '444', 'regency_id' => '7505', 'province_id' => '75', 'name' => 'KAB. GORONTALO UTARA', ],
            [ 'id' => '445', 'regency_id' => '7571', 'province_id' => '75', 'name' => 'KOTA GORONTALO', ],
            [ 'id' => '446', 'regency_id' => '7601', 'province_id' => '76', 'name' => 'KAB. PASANGKAYU', ],
            [ 'id' => '447', 'regency_id' => '7602', 'province_id' => '76', 'name' => 'KAB. MAMUJU', ],
            [ 'id' => '448', 'regency_id' => '7603', 'province_id' => '76', 'name' => 'KAB. MAMASA', ],
            [ 'id' => '449', 'regency_id' => '7604', 'province_id' => '76', 'name' => 'KAB. POLEWALI MANDAR', ],
            [ 'id' => '450', 'regency_id' => '7605', 'province_id' => '76', 'name' => 'KAB. MAJENE', ],
            [ 'id' => '451', 'regency_id' => '7606', 'province_id' => '76', 'name' => 'KAB. MAMUJU TENGAH', ],
            [ 'id' => '452', 'regency_id' => '8101', 'province_id' => '81', 'name' => 'KAB. MALUKU TENGAH', ],
            [ 'id' => '453', 'regency_id' => '8102', 'province_id' => '81', 'name' => 'KAB. MALUKU TENGGARA', ],
            [ 'id' => '454', 'regency_id' => '8103', 'province_id' => '81', 'name' => 'KAB. KEPULAUAN TANIMBAR', ],
            [ 'id' => '455', 'regency_id' => '8104', 'province_id' => '81', 'name' => 'KAB. BURU', ],
            [ 'id' => '456', 'regency_id' => '8105', 'province_id' => '81', 'name' => 'KAB. SERAM BAGIAN TIMUR', ],
            [ 'id' => '457', 'regency_id' => '8106', 'province_id' => '81', 'name' => 'KAB. SERAM BAGIAN BARAT', ],
            [ 'id' => '458', 'regency_id' => '8107', 'province_id' => '81', 'name' => 'KAB. KEPULAUAN ARU', ],
            [ 'id' => '459', 'regency_id' => '8108', 'province_id' => '81', 'name' => 'KAB. MALUKU BARAT DAYA', ],
            [ 'id' => '460', 'regency_id' => '8109', 'province_id' => '81', 'name' => 'KAB. BURU SELATAN', ],
            [ 'id' => '461', 'regency_id' => '8171', 'province_id' => '81', 'name' => 'KOTA AMBON', ],
            [ 'id' => '462', 'regency_id' => '8172', 'province_id' => '81', 'name' => 'KOTA TUAL', ],
            [ 'id' => '463', 'regency_id' => '8201', 'province_id' => '82', 'name' => 'KAB. HALMAHERA BARAT', ],
            [ 'id' => '464', 'regency_id' => '8202', 'province_id' => '82', 'name' => 'KAB. HALMAHERA TENGAH', ],
            [ 'id' => '465', 'regency_id' => '8203', 'province_id' => '82', 'name' => 'KAB. HALMAHERA UTARA', ],
            [ 'id' => '466', 'regency_id' => '8204', 'province_id' => '82', 'name' => 'KAB. HALMAHERA SELATAN', ],
            [ 'id' => '467', 'regency_id' => '8205', 'province_id' => '82', 'name' => 'KAB. KEPULAUAN SULA', ],
            [ 'id' => '468', 'regency_id' => '8206', 'province_id' => '82', 'name' => 'KAB. HALMAHERA TIMUR', ],
            [ 'id' => '469', 'regency_id' => '8207', 'province_id' => '82', 'name' => 'KAB. PULAU MOROTAI', ],
            [ 'id' => '470', 'regency_id' => '8208', 'province_id' => '82', 'name' => 'KAB. PULAU TALIABU', ],
            [ 'id' => '471', 'regency_id' => '8271', 'province_id' => '82', 'name' => 'KOTA TERNATE', ],
            [ 'id' => '472', 'regency_id' => '8272', 'province_id' => '82', 'name' => 'KOTA TIDORE KEPULAUAN', ],
            [ 'id' => '473', 'regency_id' => '9103', 'province_id' => '91', 'name' => 'KAB. JAYAPURA', ],
            [ 'id' => '474', 'regency_id' => '9105', 'province_id' => '91', 'name' => 'KAB. KEPULAUAN YAPEN', ],
            [ 'id' => '475', 'regency_id' => '9106', 'province_id' => '91', 'name' => 'KAB. BIAK NUMFOR', ],
            [ 'id' => '476', 'regency_id' => '9110', 'province_id' => '91', 'name' => 'KAB. SARMI', ],
            [ 'id' => '477', 'regency_id' => '9111', 'province_id' => '91', 'name' => 'KAB. KEEROM', ],
            [ 'id' => '478', 'regency_id' => '9115', 'province_id' => '91', 'name' => 'KAB. WAROPEN', ],
            [ 'id' => '479', 'regency_id' => '9119', 'province_id' => '91', 'name' => 'KAB. SUPIORI', ],
            [ 'id' => '480', 'regency_id' => '9120', 'province_id' => '91', 'name' => 'KAB. MAMBERAMO RAYA', ],
            [ 'id' => '481', 'regency_id' => '9171', 'province_id' => '91', 'name' => 'KOTA JAYAPURA', ],
            [ 'id' => '482', 'regency_id' => '9202', 'province_id' => '92', 'name' => 'KAB. MANOKWARI', ],
            [ 'id' => '483', 'regency_id' => '9203', 'province_id' => '92', 'name' => 'KAB. FAK FAK', ],
            [ 'id' => '484', 'regency_id' => '9206', 'province_id' => '92', 'name' => 'KAB. TELUK BINTUNI', ],
            [ 'id' => '485', 'regency_id' => '9207', 'province_id' => '92', 'name' => 'KAB. TELUK WONDAMA', ],
            [ 'id' => '486', 'regency_id' => '9208', 'province_id' => '92', 'name' => 'KAB. KAIMANA', ],
            [ 'id' => '487', 'regency_id' => '9211', 'province_id' => '92', 'name' => 'KAB. MANOKWARI SELATAN', ],
            [ 'id' => '488', 'regency_id' => '9212', 'province_id' => '92', 'name' => 'KAB. PEGUNUNGAN ARFAK', ],
            [ 'id' => '489', 'regency_id' => '9301', 'province_id' => '93', 'name' => 'KAB. MERAUKE', ],
            [ 'id' => '490', 'regency_id' => '9302', 'province_id' => '93', 'name' => 'KAB. BOVEN DIGOEL', ],
            [ 'id' => '491', 'regency_id' => '9303', 'province_id' => '93', 'name' => 'KAB. MAPPI', ],
            [ 'id' => '492', 'regency_id' => '9304', 'province_id' => '93', 'name' => 'KAB. ASMAT', ],
            [ 'id' => '493', 'regency_id' => '9401', 'province_id' => '94', 'name' => 'KAB. NABIRE', ],
            [ 'id' => '494', 'regency_id' => '9402', 'province_id' => '94', 'name' => 'KAB. PUNCAK JAYA', ],
            [ 'id' => '495', 'regency_id' => '9403', 'province_id' => '94', 'name' => 'KAB. PANIAI', ],
            [ 'id' => '496', 'regency_id' => '9404', 'province_id' => '94', 'name' => 'KAB. MIMIKA', ],
            [ 'id' => '497', 'regency_id' => '9405', 'province_id' => '94', 'name' => 'KAB. PUNCAK', ],
            [ 'id' => '498', 'regency_id' => '9406', 'province_id' => '94', 'name' => 'KAB. DOGIYAI', ],
            [ 'id' => '499', 'regency_id' => '9407', 'province_id' => '94', 'name' => 'KAB. INTAN JAYA', ],
            [ 'id' => '500', 'regency_id' => '9408', 'province_id' => '94', 'name' => 'KAB. DEIYAI', ],
            [ 'id' => '501', 'regency_id' => '9501', 'province_id' => '95', 'name' => 'KAB. JAYAWIJAYA', ],
            [ 'id' => '502', 'regency_id' => '9502', 'province_id' => '95', 'name' => 'KAB PEGUNUNGAN BINTANG', ],
            [ 'id' => '503', 'regency_id' => '9503', 'province_id' => '95', 'name' => 'KAB. YAHUKIMO', ],
            [ 'id' => '504', 'regency_id' => '9504', 'province_id' => '95', 'name' => 'KAB. TOLIKARA', ],
            [ 'id' => '505', 'regency_id' => '9505', 'province_id' => '95', 'name' => 'KAB. MAMBERAMO TENGAH', ],
            [ 'id' => '506', 'regency_id' => '9506', 'province_id' => '95', 'name' => 'KAB. YALIMO', ],
            [ 'id' => '507', 'regency_id' => '9507', 'province_id' => '95', 'name' => 'KAB. LANNY JAYA', ],
            [ 'id' => '508', 'regency_id' => '9508', 'province_id' => '95', 'name' => 'KAB. NDUGA', ],
            [ 'id' => '509', 'regency_id' => '9601', 'province_id' => '96', 'name' => 'KAB. SORONG', ],
            [ 'id' => '510', 'regency_id' => '9604', 'province_id' => '96', 'name' => 'KAB. SORONG SELATAN', ],
            [ 'id' => '511', 'regency_id' => '9605', 'province_id' => '96', 'name' => 'KAB. RAJA AMPAT', ],
            [ 'id' => '512', 'regency_id' => '9609', 'province_id' => '96', 'name' => 'KAB. TAMBRAUW', ],
            [ 'id' => '513', 'regency_id' => '9610', 'province_id' => '96', 'name' => 'KAB. MAYBRAT', ],
            [ 'id' => '514', 'regency_id' => '9671', 'province_id' => '96', 'name' => 'KOTA SORONG', ],


        ];

        foreach($regencies as $regency){
            Regency::insert($regency);
        }
    }
}
